services:
  db:
    image: postgres:12-bullseye
    container_name: psql-spotify-tracks
    environment:
      POSTGRES_DB: tracksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
